project:
  type: website
  render:
    - index.qmd
    - Overview.qmd
    - Prerequisites/Prerequisites.qmd
    - Day1.qmd

profile:
  default: en

# WEBSITE ARCHITECTURE

website:
  title: "Applied Bayesian Analyses with R (Turku 2025)"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  navbar:
    background: white
    search: true
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: Overview.qmd
        text: Overview
      - href: Prerequisites/Prerequisites.qmd
        text: Prerequisites
      - href: Day1.qmd
        text: Day1

    tools:
      - icon: github
        href: https://github.com/Sdemaeyer2/ABAR_TURKU_2025

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

author: Sven De Maeyer
title-block-banner: "#e9f3fa"

