project:
  type: website
  render:
    - index.qmd
    - Overview.qmd
    - Prerequisites/Prerequisites.qmd
    - Day1.qmd
    - Day2.qmd
    - Day3.qmd
    - about.qmd

profile:
  default: en

# WEBSITE ARCHITECTURE

website:
  favicon: "abar-favicon.png"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Sven De Maeyer, 2025"
  
  sidebar:
    logo: "Abar_Logo_2025_T.png"
    pinned: true
    align: center
    background: "#e9f3fa"
    search: true
    tools:
      - icon: github
        href: https://github.com/Sdemaeyer2/ABAR_TURKU_2025

    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - href: Overview.qmd
        text: Overview
      - href: Prerequisites/Prerequisites.qmd
        text: Prerequisites
      - href: Day1.qmd
        text: Day1
      - href: Day2.qmd
        text: Day2
      - href: Day3.qmd
        text: Day3

      - href: about.qmd
        text: About me

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


