project:
  type: website
  render:
    - index.qmd
    - Overview.qmd
    - Prerequisites/Prerequisites.qmd
    - Day1.qmd
    - Day2.qmd

profile:
  default: en

# WEBSITE ARCHITECTURE

website:
  title: "Applied Bayesian Analyses with R (Turku 2025)"
  favicon: "abar-favicon.png"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Sven De Maeyer, 2025"

  navbar:
    search: true
    background: white
    tools:
      - icon: github
        href: https://github.com/Sdemaeyer2/ABAR_TURKU_2025
  
  sidebar:
    background: "#e9f3fa"
    logo: "Abar_Logo_2025_T.png"
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: Overview.qmd
        text: Overview
      - href: Prerequisites/Prerequisites.qmd
        text: Prerequisites
      - href: Day1.qmd
        text: Day1
      - href: Day2.qmd
        text: Day2
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


